import assert from 'node:assert/strict';
import {taskValues,pageTaskValues,taskProperties,taskPatch,merge,mappedActor} from '../supabase/functions/operations-notion/model.js';
const task={id:'test-id',version:1,title:'대차 배차 진행',center_code:'001',work_date:'2026-10-11',status:'pending',inputs:{'기사명':'손성준','정산방식':'월대공제',steps:{confirm:'pending'},private_context:{course_id:'original-id'}}};
const properties=taskProperties(task), page={properties,last_edited_by:{id:'notion-person'}};
const base=taskValues(task);
assert.deepEqual(pageTaskValues(page),base);
const remote={...base,'정산방식':'기사직접'};
const web={...base,'사유':'차량 고장'};
let result=merge(base,web,remote);
assert.deepEqual(result.conflicts,[]);
assert.equal(result.values['정산방식'],'기사직접');
assert.equal(result.values['사유'],'차량 고장');
assert.deepEqual(taskPatch(task,result.values).inputs.steps,task.inputs.steps);
assert.deepEqual(taskPatch(task,result.values).inputs.private_context,task.inputs.private_context);
assert.deepEqual(merge(base,remote,remote).conflicts,[]);
assert.deepEqual(merge(base,{...base,'기사명':'A'},{...base,'기사명':'B'}).conflicts,['기사명']);
assert.throws(()=>pageTaskValues({...page,archived:true}),/활성/);
assert.throws(()=>pageTaskValues({properties:{...properties,'업무일':{date:{start:'2026-02-30'}}}}),/업무일/);
assert.throws(()=>pageTaskValues({properties:{...properties,'센터':{select:{name:'미확인센터'}}}}),/센터/);
assert.throws(()=>pageTaskValues({properties:{...properties,'정산방식':{select:{name:'미확인결제'}}}}),/정산/);
assert.throws(()=>mappedActor(page,new Map()),/계정 연결/);
assert.throws(()=>mappedActor(page,new Map([['notion-person',{user_id:'web-person',active:false}]])),/계정 연결/);
assert.equal(mappedActor(page,new Map([['notion-person',{user_id:'web-person',active:true}]])),'web-person');
console.log('PASS: Notion task round trip, three-way merge/conflicts, preserved internal inputs, actual editor mapping and invalid data refusal');
